# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('choose', '0002_auto_20170808_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=32)),
                ('check_path', models.CharField(blank=True, max_length=512, null=True)),
                ('score', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=32, null=True)),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('check_time', models.DateTimeField(blank=True, null=True)),
                ('rock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choose.Rocks')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='choose.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='choose.User')),
            ],
        ),
    ]
