# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='check_path',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='检查后的文件'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='check_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='作业批阅时间'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='order',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=32, verbose_name='第几次作业'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='rock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choose.Rocks', verbose_name='模块'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='score',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=32, null=True, verbose_name='作业成绩'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='choose.User', verbose_name='批阅老师'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='upload_time',
            field=models.DateTimeField(auto_now=True, verbose_name='作业上传时间'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='choose.User', verbose_name='学员'),
        ),
    ]
