# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_auto_20170808_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='upload_time',
            field=models.DateTimeField(verbose_name='作业上传时间'),
        ),
    ]
