# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rock_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Rows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_zone', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TestBeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_name', models.CharField(max_length=32)),
                ('rock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choose.Rocks')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=128)),
                ('c_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Weekdays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='rows',
            name='test_bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choose.TestBeds'),
        ),
        migrations.AddField(
            model_name='nodes',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='choose.User'),
        ),
        migrations.AddField(
            model_name='nodes',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choose.Rows'),
        ),
        migrations.AddField(
            model_name='nodes',
            name='weekday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choose.Weekdays'),
        ),
    ]
