# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='choose.User', verbose_name='拥有者'),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choose.Rows', verbose_name='时间段'),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='weekday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choose.Weekdays', verbose_name='星期'),
        ),
        migrations.AlterField(
            model_name='rocks',
            name='rock_name',
            field=models.CharField(max_length=64, verbose_name='种类'),
        ),
        migrations.AlterField(
            model_name='rows',
            name='test_bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choose.TestBeds', verbose_name='试验台'),
        ),
        migrations.AlterField(
            model_name='rows',
            name='time_zone',
            field=models.CharField(max_length=32, verbose_name='时间段'),
        ),
        migrations.AlterField(
            model_name='testbeds',
            name='bed_name',
            field=models.CharField(max_length=32, verbose_name='试验台'),
        ),
        migrations.AlterField(
            model_name='testbeds',
            name='rock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choose.Rocks', verbose_name='种类'),
        ),
        migrations.AlterField(
            model_name='user',
            name='c_name',
            field=models.CharField(max_length=128, verbose_name='中文名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='e_name',
            field=models.CharField(max_length=128, verbose_name='英文名'),
        ),
        migrations.AlterField(
            model_name='weekdays',
            name='day_name',
            field=models.CharField(max_length=32, verbose_name='星期'),
        ),
    ]
